/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2025-08-05 11:02:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import main.dao.Dao;
import main.Model;
import org.apache.tomcat.util.log.UserDataHelper.Mode;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("main.Model");
    _jspx_imports_classes.add("org.apache.tomcat.util.log.UserDataHelper.Mode");
    _jspx_imports_classes.add("main.dao.Dao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>Bootstrap CRUD Data Table for Database with Modal Form</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Roboto|Varela+Round\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	color: #566787;\r\n");
      out.write("	background: #f5f5f5;\r\n");
      out.write("	font-family: 'Varela Round', sans-serif;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-responsive {\r\n");
      out.write("	margin: 30px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-wrapper {\r\n");
      out.write("	background: #fff;\r\n");
      out.write("	padding: 20px 25px;\r\n");
      out.write("	border-radius: 3px;\r\n");
      out.write("	min-width: 1000px;\r\n");
      out.write("	box-shadow: 0 1px 1px rgba(0, 0, 0, .05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-title {\r\n");
      out.write("	padding-bottom: 15px;\r\n");
      out.write("	background: #435d7d;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	padding: 16px 30px;\r\n");
      out.write("	min-width: 100%;\r\n");
      out.write("	margin: -20px -25px 10px;\r\n");
      out.write("	border-radius: 3px 3px 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-title h2 {\r\n");
      out.write("	margin: 5px 0 0;\r\n");
      out.write("	font-size: 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-title .btn-group {\r\n");
      out.write("	float: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-title .btn {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	float: right;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	min-width: 50px;\r\n");
      out.write("	border-radius: 2px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	outline: none !important;\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-title .btn i {\r\n");
      out.write("	float: left;\r\n");
      out.write("	font-size: 21px;\r\n");
      out.write("	margin-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-title .btn span {\r\n");
      out.write("	float: left;\r\n");
      out.write("	margin-top: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.table tr th, table.table tr td {\r\n");
      out.write("	border-color: #e9e9e9;\r\n");
      out.write("	padding: 12px 15px;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.table tr th:first-child {\r\n");
      out.write("	width: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.table tr th:last-child {\r\n");
      out.write("	width: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.table-striped tbody tr:nth-of-type(odd) {\r\n");
      out.write("	background-color: #fcfcfc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.table-striped.table-hover tbody tr:hover {\r\n");
      out.write("	background: #f5f5f5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.table th i {\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	margin: 0 5px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.table td:last-child i {\r\n");
      out.write("	opacity: 0.9;\r\n");
      out.write("	font-size: 22px;\r\n");
      out.write("	margin: 0 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.table td a {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: #566787;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	outline: none !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.table td a:hover {\r\n");
      out.write("	color: #2196F3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.table td a.edit {\r\n");
      out.write("	color: #FFC107;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.table td a.delete {\r\n");
      out.write("	color: #F44336;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.table td i {\r\n");
      out.write("	font-size: 19px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table.table .avatar {\r\n");
      out.write("	border-radius: 50%;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination {\r\n");
      out.write("	float: right;\r\n");
      out.write("	margin: 0 0 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination li a {\r\n");
      out.write("	border: none;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	min-width: 30px;\r\n");
      out.write("	min-height: 30px;\r\n");
      out.write("	color: #999;\r\n");
      out.write("	margin: 0 2px;\r\n");
      out.write("	line-height: 30px;\r\n");
      out.write("	border-radius: 2px !important;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 0 6px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination li a:hover {\r\n");
      out.write("	color: #666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination li.active a, .pagination li.active a.page-link {\r\n");
      out.write("	background: #03A9F4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination li.active a:hover {\r\n");
      out.write("	background: #0397d6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination li.disabled i {\r\n");
      out.write("	color: #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination li i {\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	padding-top: 6px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hint-text {\r\n");
      out.write("	float: left;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("/* Custom checkbox */\r\n");
      out.write(".custom-checkbox {\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".custom-checkbox input[type=\"checkbox\"] {\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	margin: 5px 0 0 3px;\r\n");
      out.write("	z-index: 9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".custom-checkbox label:before {\r\n");
      out.write("	width: 18px;\r\n");
      out.write("	height: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".custom-checkbox label:before {\r\n");
      out.write("	content: '';\r\n");
      out.write("	margin-right: 10px;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	vertical-align: text-top;\r\n");
      out.write("	background: white;\r\n");
      out.write("	border: 1px solid #bbb;\r\n");
      out.write("	border-radius: 2px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	z-index: 2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".custom-checkbox input[type=\"checkbox\"]:checked+label:after {\r\n");
      out.write("	content: '';\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 6px;\r\n");
      out.write("	top: 3px;\r\n");
      out.write("	width: 6px;\r\n");
      out.write("	height: 11px;\r\n");
      out.write("	border: solid #000;\r\n");
      out.write("	border-width: 0 3px 3px 0;\r\n");
      out.write("	transform: inherit;\r\n");
      out.write("	z-index: 3;\r\n");
      out.write("	transform: rotateZ(45deg);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".custom-checkbox input[type=\"checkbox\"]:checked+label:before {\r\n");
      out.write("	border-color: #03A9F4;\r\n");
      out.write("	background: #03A9F4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".custom-checkbox input[type=\"checkbox\"]:checked+label:after {\r\n");
      out.write("	border-color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".custom-checkbox input[type=\"checkbox\"]:disabled+label:before {\r\n");
      out.write("	color: #b8b8b8;\r\n");
      out.write("	cursor: auto;\r\n");
      out.write("	box-shadow: none;\r\n");
      out.write("	background: #ddd;\r\n");
      out.write("}\r\n");
      out.write("/* Modal styles */\r\n");
      out.write(".modal .modal-dialog {\r\n");
      out.write("	max-width: 400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal .modal-header, .modal .modal-body, .modal .modal-footer {\r\n");
      out.write("	padding: 20px 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal .modal-content {\r\n");
      out.write("	border-radius: 3px;\r\n");
      out.write("	font-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal .modal-footer {\r\n");
      out.write("	background: #ecf0f1;\r\n");
      out.write("	border-radius: 0 0 3px 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal .modal-title {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal .form-control {\r\n");
      out.write("	border-radius: 2px;\r\n");
      out.write("	box-shadow: none;\r\n");
      out.write("	border-color: #dddddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal textarea.form-control {\r\n");
      out.write("	resize: vertical;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal .btn {\r\n");
      out.write("	border-radius: 2px;\r\n");
      out.write("	min-width: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal form label {\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		// Activate tooltip\r\n");
      out.write("		$('[data-toggle=\"tooltip\"]').tooltip();\r\n");
      out.write("\r\n");
      out.write("		// Select/Deselect checkboxes\r\n");
      out.write("		var checkbox = $('table tbody input[type=\"checkbox\"]');\r\n");
      out.write("		$(\"#selectAll\").click(function() {\r\n");
      out.write("			if (this.checked) {\r\n");
      out.write("				checkbox.each(function() {\r\n");
      out.write("					this.checked = true;\r\n");
      out.write("				});\r\n");
      out.write("			} else {\r\n");
      out.write("				checkbox.each(function() {\r\n");
      out.write("					this.checked = false;\r\n");
      out.write("				});\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		checkbox.click(function() {\r\n");
      out.write("			if (!this.checked) {\r\n");
      out.write("				$(\"#selectAll\").prop(\"checked\", false);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container-xl\">\r\n");
      out.write("		<div class=\"table-responsive\">\r\n");
      out.write("			<div class=\"table-wrapper\">\r\n");
      out.write("				<div class=\"table-title\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<h2>\r\n");
      out.write("								Manage <b>Employees</b>\r\n");
      out.write("							</h2>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<a href=\"#addEmployeeModal\" class=\"btn btn-success\"\r\n");
      out.write("								data-toggle=\"modal\"><i class=\"material-icons\">&#xE147;</i> <span>Add\r\n");
      out.write("									New Employee</span></a> <a href=\"#deleteEmployeeModal\"\r\n");
      out.write("								class=\"btn btn-danger\" data-toggle=\"modal\"><i\r\n");
      out.write("								class=\"material-icons\">&#xE15C;</i> <span>Delete</span></a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<table class=\"table table-striped table-hover\">\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th><span class=\"custom-checkbox\"> <input\r\n");
      out.write("									type=\"checkbox\" id=\"selectAll\"> <label for=\"selectAll\"></label>\r\n");
      out.write("							</span></th>\r\n");
      out.write("							\r\n");
      out.write("							<th>Name</th>\r\n");
      out.write("							<th>Email</th>\r\n");
      out.write("							<th>Address</th>\r\n");
      out.write("							<th>Phone</th>\r\n");
      out.write("							<th>Actions</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<tbody>\r\n");
      out.write("						");

						List<Model> v = Dao.viewall();

						for (Model s : v) {
						
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td><span class=\"custom-checkbox\"> <input\r\n");
      out.write("									type=\"checkbox\" id=\"checkbox_");
      out.print(s.getId());
      out.write("\"> <label\r\n");
      out.write("									for=\"checkbox_");
      out.print(s.getId());
      out.write("\"></label>\r\n");
      out.write("							</span></td>\r\n");
      out.write("							<td>");
      out.print(s.getName());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(s.getEmail());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(s.getAddress());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(s.getPhone());
      out.write("</td>\r\n");
      out.write("							<td>\r\n");
      out.write("							 \r\n");
      out.write("							<form action=\"delete.jsp\">\r\n");
      out.write("					\r\n");
      out.write("							<input type=\"hidden\" name=\"id\" value=\"");
      out.print(s.getId());
      out.write("\">\r\n");
      out.write("							<input type=\"submit\" value=\"delete\" class=\"btn btn-outline-danger\">\r\n");
      out.write("							\r\n");
      out.write("					        </form>\r\n");
      out.write("					\r\n");
      out.write("							<form action=\"edit.jsp\">\r\n");
      out.write("					\r\n");
      out.write("							<input type=\"hidden\" name=\"id\" value=\"");
      out.print(s.getId());
      out.write("\">\r\n");
      out.write("							\r\n");
      out.write("							<input type=\"submit\" value=\"edit\" class=\"btn btn-outline-primary ms-2\">\r\n");
      out.write("							\r\n");
      out.write("					        </form>\r\n");
      out.write("					                \r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("\r\n");
      out.write("						");

						}
						
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Add Modal HTML -->\r\n");
      out.write("	<div id=\"addEmployeeModal\" class=\"modal fade\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<form action=\"insert.jsp\">\r\n");
      out.write("					<div class=\"modal-header\">\r\n");
      out.write("						<h4 class=\"modal-title\">Add Employee</h4>\r\n");
      out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("							aria-hidden=\"true\">&times;</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-body\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label>Name</label> <input type=\"text\" name=\"name\"\r\n");
      out.write("								class=\"form-control\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label>Email</label> <input type=\"email\" name=\"email\"\r\n");
      out.write("								class=\"form-control\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label>Address</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("								name=\"address\" required>\r\n");
      out.write("							</textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label>Phone</label> <input type=\"text\" name=\"phone\"\r\n");
      out.write("								class=\"form-control\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-footer\">\r\n");
      out.write("						<input type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\"\r\n");
      out.write("							value=\"Cancel\"> <input type=\"submit\"\r\n");
      out.write("							class=\"btn btn-success\" value=\"Add\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Edit Modal HTML -->\r\n");
      out.write("	<div id=\"editEmployeeModal\" class=\"modal fade\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<form>\r\n");
      out.write("					<div class=\"modal-header\">\r\n");
      out.write("						<h4 class=\"modal-title\">Edit Employee</h4>\r\n");
      out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("							aria-hidden=\"true\">&times;</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-body\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label>Name</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("								required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label>Email</label> <input type=\"email\" class=\"form-control\"\r\n");
      out.write("								required>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label>Address</label>\r\n");
      out.write("							<textarea class=\"form-control\" required></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label>Phone</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("								required>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-footer\">\r\n");
      out.write("						<input type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\"\r\n");
      out.write("							value=\"Cancel\"> <input type=\"submit\" class=\"btn btn-info\"\r\n");
      out.write("							value=\"Save\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Delete Modal HTML -->\r\n");
      out.write("	<div id=\"deleteEmployeeModal\" class=\"modal fade\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<form class=\"delete.jsp\">\r\n");
      out.write("					<div class=\"modal-header\">\r\n");
      out.write("						<h4 class=\"modal-title\">Delete Employee</h4>\r\n");
      out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("							aria-hidden=\"true\">&times;</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-body\">\r\n");
      out.write("						<p>Are you sure you want to delete these Records?</p>\r\n");
      out.write("						<p class=\"text-warning\">\r\n");
      out.write("							<small>This action cannot be undone.</small>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-footer\">\r\n");
      out.write("						<input type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\"\r\n");
      out.write("							value=\"Cancel\"> <input type=\"submit\"\r\n");
      out.write("							class=\"btn btn-danger\" value=\"Delete\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
